IIITHAttendancePortal/urls.py
from django.contrib import admin
from django.urls import path, include
from django.contrib.auth import views as auth_views

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('info.urls')),
    path('info/', include('info.urls')),
    path('accounts/login/', auth_views.LoginView.as_view(template_name='info/login.html'), name='login'),
    path('accounts/logout/', auth_views.LogoutView.as_view(template_name='info/logout.html'), name='logout'),
]

info/urls.py
from django.urls import path
from . import views


urlpatterns = [
    path('', views.index, name='index'),
    path('student/<slug:stud_id>/attendance/', views.attendance, name='attendance'),
    path('student/<slug:stud_id>/<slug:course_id>/attendance/', views.attendance_detail, name='attendance_detail'),
    path('teacher/<slug:teacher_id>/<int:choice>/Classes/', views.t_clas, name='t_clas'),
    path('teacher/<int:assign_id>/Students/attendance/', views.t_student, name='t_student'),
    path('teacher/<int:assign_id>/ClassDates/', views.t_class_date, name='t_class_date'),
    path('teacher/<int:ass_c_id>/Cancel/', views.cancel_class, name='cancel_class'),
    path('teacher/<int:ass_c_id>/attendance/', views.t_attendance, name='t_attendance'),
    path('teacher/<int:pk>/attendance/upload/', views.AttendanceClassUpdateView.as_view(), name='att_upload'),
    path('teacher/<int:ass_c_id>/attendance/auto', views.t_attendance_auto, name='t_attendance_auto'),
    path('teacher/<int:ass_c_id>/Edit_att/', views.edit_att, name='edit_att'),
    path('teacher/<int:ass_c_id>/attendance/confirm/', views.confirm, name='confirm'),
    path('teacher/<slug:stud_id>/<slug:course_id>/attendance/', views.t_attendance_detail, name='t_attendance_detail'),
    path('teacher/<int:att_id>/change_attendance/', views.change_att, name='change_att'),
    path('teacher/<int:assign_id>/Report/', views.t_report, name='t_report')
]

info/models.py
from django.db import models
import math
from django.core.validators import MinValueValidator, MaxValueValidator
from django.contrib.auth.models import AbstractUser
from django.db.models.signals import post_save, post_delete
from datetime import timedelta, date

# Create your models here.
sex_choice = (
    ('Male', 'Male'),
    ('Female', 'Female')
)

time_slots = (
    ('8:30 - 10:00', '8:30 - 10:00'),
    ('10:00 - 11:30', '10:00 - 11:30'),
    ('11:30 - 1:00', '11:30 - 1:00'),
    ('2:00 - 3:30', '2:00 - 3:30'),
    ('3:30 - 5:00', '3:30 - 5:00'),    
)

DAYS_OF_WEEK = (
    ('Monday', 'Monday'),
    ('Tuesday', 'Tuesday'),
    ('Wednesday', 'Wednesday'),
    ('Thursday', 'Thursday'),
    ('Friday', 'Friday'),
    ('Saturday', 'Saturday'),
)

test_name = (
    ('Internal test 1', 'Internal test 1'),
    ('Internal test 2', 'Internal test 2'),
    ('Internal test 3', 'Internal test 3'),
    ('Event 1', 'Event 1'),
    ('Event 2', 'Event 2'),
    ('Semester End Exam', 'Semester End Exam'),
)


class User(AbstractUser):
    @property
    def is_student(self):
        if hasattr(self, 'student'):
            return True
        return False

    @property
    def is_teacher(self):
        if hasattr(self, 'teacher'):
            return True
        return False


class Dept(models.Model):
    id = models.CharField(primary_key='True', max_length=100)
    name = models.CharField(max_length=200)

    def __str__(self):
        return self.name


class Course(models.Model):
    dept = models.ForeignKey(Dept, on_delete=models.CASCADE)
    id = models.CharField(primary_key='True', max_length=50)
    name = models.CharField(max_length=50)
    shortname = models.CharField(max_length=50, default='X')

    def __str__(self):
        return self.name


class Class(models.Model):
    # courses = models.ManyToManyField(Course, default=1)
    id = models.CharField(primary_key='True', max_length=100)
    dept = models.ForeignKey(Dept, on_delete=models.CASCADE)
    section = models.CharField(max_length=100)
    sem = models.IntegerField()

    class Meta:
        verbose_name_plural = 'classes'

    def __str__(self):
        d = Dept.objects.get(name=self.dept)
        return '%s : %d %s' % (d.name, self.sem, self.section)


class Student(models.Model):
    user = models.OneToOneField(User, on_delete=models.CASCADE, null=True)
    class_id = models.ForeignKey(Class, on_delete=models.CASCADE, default=1)
    USN = models.CharField(primary_key='True', max_length=100)
    name = models.CharField(max_length=200)
    sex = models.CharField(max_length=50, choices=sex_choice, default='Male')
    DOB = models.DateField(default='1998-01-01')

    def __str__(self):
        return self.name


class Teacher(models.Model):
    user = models.OneToOneField(User, on_delete=models.CASCADE, null=True)
    id = models.CharField(primary_key=True, max_length=100)
    dept = models.ForeignKey(Dept, on_delete=models.CASCADE, default=1)
    name = models.CharField(max_length=100)
    sex = models.CharField(max_length=50, choices=sex_choice, default='Male')
    DOB = models.DateField(default='1980-01-01')

    def __str__(self):
        return self.name


class Assign(models.Model):
    class_id = models.ForeignKey(Class, on_delete=models.CASCADE)
    course = models.ForeignKey(Course, on_delete=models.CASCADE)
    teacher = models.ForeignKey(Teacher, on_delete=models.CASCADE)

    class Meta:
        unique_together = (('course', 'class_id', 'teacher'),)

    def __str__(self):
        cl = Class.objects.get(id=self.class_id_id)
        cr = Course.objects.get(id=self.course_id)
        te = Teacher.objects.get(id=self.teacher_id)
        return '%s : %s : %s' % (te.name, cr.shortname, cl)


class AssignTime(models.Model):
    assign = models.ForeignKey(Assign, on_delete=models.CASCADE)
    period = models.CharField(max_length=50, choices=time_slots, default='11:00 - 11:50')
    day = models.CharField(max_length=15, choices=DAYS_OF_WEEK)


class AttendanceClass(models.Model):
    assign = models.ForeignKey(Assign, on_delete=models.CASCADE)
    date = models.DateField()
    image = models.ImageField(
        null=True,
        blank=True,
        upload_to='Images',
    )
    status = models.IntegerField(default=0)


class Attendance(models.Model):
    course = models.ForeignKey(Course, on_delete=models.CASCADE)
    student = models.ForeignKey(Student, on_delete=models.CASCADE)
    attendanceclass = models.ForeignKey(AttendanceClass, on_delete=models.CASCADE, default=1)
    date = models.DateField(default='2020-1-1')
    status = models.BooleanField(default='True')

    def __str__(self):
        sname = Student.objects.get(name=self.student)
        cname = Course.objects.get(name=self.course)
        return '%s : %s' % (sname.name, cname.shortname)


class AttendanceTotal(models.Model):
    course = models.ForeignKey(Course, on_delete=models.CASCADE)
    student = models.ForeignKey(Student, on_delete=models.CASCADE)

    class Meta:
        unique_together = (('student', 'course'),)

    @property
    def att_class(self):
        stud = Student.objects.get(name=self.student)
        cr = Course.objects.get(name=self.course)
        att_class = Attendance.objects.filter(course=cr, student=stud, status='True').count()
        return att_class

    @property
    def total_class(self):
        stud = Student.objects.get(name=self.student)
        cr = Course.objects.get(name=self.course)
        total_class = Attendance.objects.filter(course=cr, student=stud).count()
        return total_class

    @property
    def attendance(self):
        stud = Student.objects.get(name=self.student)
        cr = Course.objects.get(name=self.course)
        total_class = Attendance.objects.filter(course=cr, student=stud).count()
        att_class = Attendance.objects.filter(course=cr, student=stud, status='True').count()
        if total_class == 0:
            attendance = 0
        else:
            attendance = round(att_class / total_class * 100, 2)
        return attendance

    @property
    def classes_to_attend(self):
        stud = Student.objects.get(name=self.student)
        cr = Course.objects.get(name=self.course)
        total_class = Attendance.objects.filter(course=cr, student=stud).count()
        att_class = Attendance.objects.filter(course=cr, student=stud, status='True').count()
        cta = math.ceil((0.75*total_class - att_class)/0.25)
        if cta < 0:
            return 0
        return cta


class StudentCourse(models.Model):
    student = models.ForeignKey(Student, on_delete=models.CASCADE)
    course = models.ForeignKey(Course, on_delete=models.CASCADE)

    class Meta:
        unique_together = (('student', 'course'),)
        verbose_name_plural = 'Marks'

    def __str__(self):
        sname = Student.objects.get(name=self.student)
        cname = Course.objects.get(name=self.course)
        return '%s : %s' % (sname.name, cname.shortname)

    def get_cie(self):
        marks_list = self.marks_set.all()
        m = []
        for mk in marks_list:
            m.append(mk.marks1)
        cie = math.ceil(sum(m[:5])/2)
        return cie

    def get_attendance(self):
        a = AttendanceTotal.objects.get(student=self.student, course=self.course)
        return a.attendance

# Triggers
def daterange(start_date, end_date):
    for n in range(int ((end_date - start_date).days)):
        yield start_date + timedelta(n)

days = {
    'Monday': 1,
    'Tuesday': 2,
    'Wednesday': 3,
    'Thursday': 4,
    'Friday': 5,
    'Saturday': 6,
}


def create_attendance(sender, instance, **kwargs):
    if kwargs['created']:
        start_date = date(2020, 8, 1)
        end_date = date(2020, 11, 30)
        for single_date in daterange(start_date, end_date):
            if single_date.isoweekday() == days[instance.day]:
                try:
                    a = AttendanceClass.objects.get(date=single_date.strftime("%Y-%m-%d"), assign=instance.assign)
                except AttendanceClass.DoesNotExist:
                    a = AttendanceClass(date=single_date.strftime("%Y-%m-%d"), assign=instance.assign)
                    a.save()

post_save.connect(create_attendance, sender=AssignTime)

info/templates/info/at_upload.html
{% extends 'info/base.html' %} {% block content %}
<div class="card mb-3">
  <div class="card-header">
    <i class="fas fa-table"></i>
    <h3><b>Upload Attendance for automated tracking</b></h3>
    <hr />
  </div>
  <div class="card-body">
    <form method="POST" enctype="multipart/form-data">
      {% csrf_token %} {{ form }}
      <br />
      <button type="submit" class="btn btn-success">Submit</button>
    </form>
  </div>
</div>
{% endblock %}

info/templates/info/att_detail.html
{% extends 'info/base.html' %}

    {% block content %}
        <div class="card mb-3">
            <div class="card-header">
              <i class="fas fa-table"></i>
            <strong>{{ cr.name }}</strong></div>
            <div class="card-body">
              <div class="table-responsive">
                <table class="table table-bordered" id="dataTable" width="100%" cellspacing="0">
                  <thead>
                    <tr>
                        <th>#</th>
                        <th>Date</th>
                        <th>Day</th>
                        <th>Status</th>
                        <th></th>
                    </tr>
                  </thead>
                  <tbody>
                        {% for a in att_list %}
                        <tr class="row100 body">
                            <td>{{ forloop.counter }}</td>
                            <td>{{ a.date }}</td>
                            <td>{{ a.date|date:"l" }}</td>
                            {% if a.status %}
                            <td class="p-3 mb-2 bg-success text-white">Present <span class="glyphicon glyphicon-thumbs-up"></span></td>
                            {% else %}
                            <td class="p-3 mb-2 bg-danger text-white">Absent <span class="glyphicon glyphicon-thumbs-down"></span</td>
                            {% endif %}
                        </tr>
                    {% empty %}
                            <p>student has no attendance</p>
                    {% endfor %}

                  </tbody>
                </table>
              </div>
            </div>
          </div>


    {% endblock %}


info/templates/info/attendance.html
{% extends 'info/base.html' %} {% load static %} {% block content %}
<div class="card mb-3">
  <div class="card-header">
    <i class="fas fa-table"></i>
    <b>Attendance</b>
  </div>
  <div class="card-body">
    <div class="table-responsive">
      <table
        class="table table-bordered text-center"
        id="dataTable"
        width="100%"
        cellspacing="0"
      >
        <thead class="thead-light">
          <tr>
            <th>Course ID</th>
            <th>Course name</th>
            <th>Attended classes</th>
            <th>Total classes</th>
            <th>Attendance %</th>
            <th>Classes to attend</th>
          </tr>
        </thead>
        <tbody>
          {% for a in att_list %}
          <tr>
            <td>{{ a.course_id }}</td>
            <td>
              <a href="{% url 'attendance_detail' a.student.USN a.course.id %}"
                >{{a.course.name}}</a
              >
            </td>
            <td>{{ a.att_class }}</td>
            <td>{{ a. }}</td>
            {% if a.attendance < 75 %}
            <td class="p-3 mb-2 bg-danger text-white">{{ a.attendance }}</td>
            {% else %}
            <td class="p-3 mb-2 bg-success text-white">{{ a.attendance }}</td>
            {% endif %}
            <td>{{ a.classes_to_attend }}</td>
          </tr>
          {% empty %}
          <p>student has no courses</p>
          {% endfor %}
        </tbody>
      </table>
    </div>
  </div>
</div>

{% endblock %}

info/templates/info/base.html
<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="utf-8" />
    <meta http-equiv="X-UA-Compatible" content="IE=edge" />
    <meta
      name="viewport"
      content="width=device-width, initial-scale=1, shrink-to-fit=no"
    />
    <meta name="description" content="" />
    <meta name="author" content="" />

    <title>{% block title %}{% endblock %}</title>

    <title>Attendance Management</title>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1" />
    <link
      rel="stylesheet"
      href="https://maxcdn.bootstrapcdn.com/bootstrap/3.4.1/css/bootstrap.min.css"
    />
    <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.4.1/jquery.min.js"></script>
    <script src="https://maxcdn.bootstrapcdn.com/bootstrap/3.4.1/js/bootstrap.min.js"></script>
    <!-- <script src="./admin.js"></script> -->

    <!-- {% load static %}
    <link href="{% static '/info/bootstrap/vendor/bootstrap/css/bootstrap.min.css' %}" rel="stylesheet">
    <link href="{% static '/info/bootstrap/vendor/fontawesome-free/css/all.min.css' %}" rel="stylesheet" type="text/css">
    <link href="{% static '/info/bootstrap/vendor/datatables/dataTables.bootstrap4.css' %}" rel="stylesheet">
    <link href="{% static '/info/bootstrap/css/sb-admin.css' %}" rel="stylesheet">  
    {% block css %}
    {% endblock %}-->
  </head>

  <body id="page-top">
    <nav class="navbar navbar-inverse">
      <a class="navbar-brand mr-1" href="{% url 'index' %}">IIITH-Attendance</a>
      <div class="container-fluid">
        <div class="navbar-header">
          <button
            type="button"
            class="navbar-toggle"
            data-toggle="collapse"
            data-target="#myNavbar"
          >
            <span class="icon-bar"></span>
            <span class="icon-bar"></span>
            <span class="icon-bar"></span>
          </button>
        </div>
        <div class="collapse navbar-collapse" id="myNavbar">
          <ul class="nav navbar-nav" id="myNavbar_ul">
            <li id="overview_attendance_navbar">
              <a href="{% url 'index' %}">Home</a>
            </li>
            {% if request.user.is_student %}
            <li id="upload_attendance_navbar">
              <a href="{% url 'attendance' request.user.student.USN %}"
                >Attendance</a
              >
            </li>
            <!-- <li id="review_attendance_navbar"><a href="{% url 'attendance' request.user.student.USN %}">Attendance by subject</a></li> -->
            {% elif request.user.is_teacher %}
            <li id="upload_attendance_navbar" class="active">
              <a href="{% url 't_clas' request.user.teacher.id 1 %}"
                >Review Attendance</a
              >
            </li>
            <li id="review_attendance_navbar">
              <a href="{% url 't_clas' request.user.teacher.id 3 %}"
                >Summary Reports</a
              >
            </li>
            {% endif %}
            <li id="contact_navbar">
              <a
                class="nav-link"
                href="#"
                data-toggle="modal"
                data-target="#logoutModal"
                >Logout</a
              >
            </li>
          </ul>
        </div>
      </div>
    </nav>

    <div id="wrapper">
      <div id="content-wrapper">
        <div class="container-fluid">
          <!-- Breadcrumbs-->
          {#
          <ol class="breadcrumb">
            #} {#
            <li class="breadcrumb-item">
              #} {# <a href="index.html">Dashboard</a>#} {#
            </li>
            #} {#
            <li class="breadcrumb-item active">Blank Page</li>
            #} {#
          </ol>
          #} {% block content %} {% endblock %}
        </div>
        {#
        <footer class="sticky-footer">
          #} {#
          <div class="container my-auto">
            #} {#
            <div class="copyright text-center my-auto">
              #} {# <span>Copyright © Your Website 2020</span>#} {#
            </div>
            #} {#
          </div>
          #} {#
        </footer>
        #}
      </div>
    </div>

    <a class="scroll-to-top rounded" href="#page-top">
      <i class="fas fa-angle-up"></i>
    </a>

    <!-- Logout Modal-->
    <div
      class="modal fade"
      id="logoutModal"
      tabindex="-1"
      role="dialog"
      aria-labelledby="exampleModalLabel"
      aria-hidden="true"
    >
      <div class="modal-dialog" role="document">
        <div class="modal-content">
          <div class="modal-header">
            <h5 class="modal-title" id="exampleModalLabel">Ready to Leave?</h5>
            <button
              class="close"
              type="button"
              data-dismiss="modal"
              aria-label="Close"
            >
              <span aria-hidden="true">×</span>
            </button>
          </div>
          <div class="modal-body">
            Select "Logout" below if you are ready to end your current session.
          </div>
          <div class="modal-footer">
            <button
              class="btn btn-secondary"
              type="button"
              data-dismiss="modal"
            >
              Cancel
            </button>
            <a class="btn btn-primary" href="/accounts/logout">Logout</a>
          </div>
        </div>
      </div>
    </div>

    <!-- Bootstrap core JavaScript-->
    <script src="{% static '/info/bootstrap/vendor/jquery/jquery.min.js' %}"></script>
    <script src="{% static '/info/bootstrap/vendor/bootstrap/js/bootstrap.bundle.min.js' %}"></script>

    <!-- Core plugin JavaScript-->
    <script src="{% static '/info/bootstrap/vendor/jquery-easing/jquery.easing.min.js' %}"></script>

    <!-- Custom scripts for all pages-->
    <script src="{% static '/info/bootstrap/js/sb-admin.min.js' %}"></script>

    {% block scripts %} {% endblock %}
  </body>
</html>

info/templates/info/homepage.html
<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="utf-8" />
    <meta
      name="viewport"
      content="width=device-width, initial-scale=1, shrink-to-fit=no"
    />
    <meta name="description" content="" />
    <meta name="author" content="" />

    <title>homepage</title>
    {% load static %}

    <!-- Bootstrap core CSS -->
    <link
      href="{% static '/info/homepage/vendor/bootstrap/css/bootstrap.min.css' %}"
      rel="stylesheet"
    />

    <!-- Custom styles for this template -->
    <link
      href="{% static '/info/homepage/css/heroic-features.css' %}"
      rel="stylesheet"
    />
    <link
      href="{% static '/info/bootstrap/vendor/fontawesome-free/css/all.min.css' %}"
      rel="stylesheet"
      type="text/css"
    />
  </head>

  <body>
    <!-- Navigation -->
    <nav class="navbar navbar-expand-lg navbar-dark bg-dark fixed-top">
      <div class="container">
        <a class="navbar-brand" href="{% url 'index' %}"
          >IIITH Attendance Portal</a
        >
        <button
          class="navbar-toggler"
          type="button"
          data-toggle="collapse"
          data-target="#navbarResponsive"
          aria-controls="navbarResponsive"
          aria-expanded="false"
          aria-label="Toggle navigation"
        >
          <span class="navbar-toggler-icon"></span>
        </button>
        <div class="collapse navbar-collapse" id="navbarResponsive">
          <ul class="navbar-nav ml-auto">
            <li class="nav-item">
              <a class="nav-link text-capitalize"
                >{{ request.user.student.name }}</a
              >
            </li>
            <li class="nav-item">
              <a
                class="nav-link"
                href="#"
                data-toggle="modal"
                data-target="#logoutModal"
                >Logout</a
              >
            </li>
          </ul>
        </div>
      </div>
    </nav>

    <!-- Page Content -->
    <div class="container">
      <!-- Jumbotron Header -->
      <header class="jumbotron my-4">
        <h1 class="display-3 text-capitalize">
          Welcome {{ request.user.student.name }}
        </h1>
      </header>

      <!-- Page Features -->
      <div class="row text-center">
        <div class="col-lg-3 col-md-6 mb-4">
          <div class="card">
            <a href="{% url 'attendance' request.user.student.USN %}">
              <img
                class="card-img-top"
                src="{% static 'info/images/attendance2.jpg' %}"
                alt=""
              />
            </a>
            <div class="card-body">
              <h4 class="card-title">Attendance</h4>
              <p class="card-text">
                View the attendance status for each of your courses. The
                attendance of each course is also displayed as list of classes
                that were conducted.
              </p>
            </div>
            <div class="card-footer">
              <a
                class="btn btn-primary"
                role="button"
                href="{% url 'attendance' request.user.student.USN %}"
              >
                View Attendance</a
              >
            </div>
          </div>
        </div>

        {% comment %}
        <div class="col-lg-3 col-md-6 mb-4">
          <div class="card">
            <a href="{% url 'marks_list' request.user.student.USN %}">
              <img
                class="card-img-top"
                src="{% static 'info/images/marks.jpg' %}"
                alt=""
              />
            </a>
            <div class="card-body">
              <h4 class="card-title">Marks</h4>
              <p class="card-text">
                View the marks obtained for each of your courses. These include
                the marks of 3 internal assessment, 2 events and the Semester
                End Exam
              </p>
            </div>
            <div class="card-footer">
              <a
                class="btn btn-primary"
                role="button"
                href="{% url 'marks_list' request.user.student.USN %}"
                >View Marks</a
              >
            </div>
          </div>
        </div>
        {% endcomment %}
      </div>
    </div>
    <!-- Logout Modal-->
    <div
      class="modal fade"
      id="logoutModal"
      tabindex="-1"
      role="dialog"
      aria-labelledby="exampleModalLabel"
      aria-hidden="true"
    >
      <div class="modal-dialog" role="document">
        <div class="modal-content">
          <div class="modal-header">
            <h5 class="modal-title" id="exampleModalLabel">Ready to Leave?</h5>
            <button
              class="close"
              type="button"
              data-dismiss="modal"
              aria-label="Close"
            >
              <span aria-hidden="true">×</span>
            </button>
          </div>
          <div class="modal-body">
            Select "Logout" below if you are ready to end your current session.
          </div>
          <div class="modal-footer">
            <button
              class="btn btn-secondary"
              type="button"
              data-dismiss="modal"
            >
              Cancel
            </button>
            <a class="btn btn-primary" href="/accounts/logout">Logout</a>
          </div>
        </div>
      </div>
    </div>

    <!-- Bootstrap core JavaScript -->

    <script src="{% static '/info/homepage/vendor/jquery/jquery.min.js' %}"></script>
    <script src="{% static '/info/homepage/vendor/bootstrap/js/bootstrap.bundle.min.js' %}"></script>
  </body>
</html>

info/templates/info/t_attendance.html
{% extends 'info/base.html' %} {% block content %} {% if c.student_set.all %}

<form action="{% url 'confirm' assc.id %}" method="post">
  {% csrf_token %}
  <div class="card mb-3">
    <div class="card-header">
      <i class="fas fa-table"></i>
      <b>{{ dept1.name }}</b>
    </div>
    <div class="card-body">
      <div class="table-responsive">
        <table
          class="table table-bordered"
          id="dataTable"
          width="100%"
          cellspacing="0"
        >
          <thead>
            <tr>
              <th>Student name</th>
              <th></th>
            </tr>
          </thead>
          <tbody>
            {% for s in c.student_set.all %}
            <tr>
              <td>{{s.name}}</td>
              <td>
                <div class="btn-group btn-group-toggle" data-toggle="buttons">
                  <label class="btn btn-default active">
                    <input
                      type="radio"
                      name="{{ s.USN }}"
                      id="option1"
                      autocomplete="off"
                      value="present"
                      checked
                    />
                    Present
                  </label>

                  <label class="btn btn-default">
                    <input
                      type="radio"
                      name="{{ s.USN }}"
                      id="option2"
                      autocomplete="off"
                      value="absent"
                    />
                    Absent
                  </label>
                </div>
              </td>
            </tr>
            {% endfor %}
          </tbody>
        </table>
      </div>
    </div>
  </div>

  <input class="btn btn-success" type="submit" value="Submit" />
</form>

{% else %}
<p>No students in Class</p>
{% endif %} {% endblock %}

info/templates/info/t_clas.html
{% extends 'info/base.html' %} {% block content %}
<h1>Courses</h1>
<div class="card mb-3">
  <div class="card-body">
    <div class="table-responsive">
      <table
        class="table table-bordered text-center"
        id="dataTable"
        width="100%"
        cellspacing="0"
      >
        <thead>
          <tr>
            <th>Class</th>
            <th>Course</th>
            <th></th>
          </tr>
        </thead>
        <tbody>
          {% for ass in teacher1.assign_set.all %}
          <tr>
            <td>{{ ass.class_id }}</td>
            <td>{{ ass.course }}</td>
            <td>
              {% if choice == 1 %}
              <a
                class="btn"
                href="{% url 't_class_date' ass.id %}"
                role="button"
                >Enter Attendance</a
              >
              {#<a
                class="btn btn-warning"
                href="{% url 't_extra_class' ass.id %}"
                >Extra Class</a
              >#}
              <a class="btn" href="{% url 't_student' ass.id %}">Students</a>

              {% elif choice == 3 %}
              <a class="btn btn-danger" href="{% url 't_report' ass.id %}"
                >Generate Summary Report</a
              >
              {% endif %}
            </td>
          </tr>
          {% empty %}
          <p>teacher has no courses</p>
          {% endfor %}
        </tbody>
      </table>
    </div>
  </div>
  {% endblock %}
</div>

info/templates/info/t_extra_class.html
{% extends 'info/base.html' %} {% block content %} {% if c.student_set.all %}

<form action="{% url 'e_confirm' ass.id %}" method="post">
  {% csrf_token %}
  <label for="date">Enter Date: </label>
  <input type="date" name="date" />

  <div class="card mb-3">
    <div class="card-header">
      <i class="fas fa-table"></i>
      <b>{{ dept1.name }}</b>
    </div>
    <div class="card-body">
      <div class="table-responsive">
        <table
          class="table table-bordered"
          id="dataTable"
          width="100%"
          cellspacing="0"
        >
          <thead>
            <tr>
              <th>Student name</th>
              <th></th>
            </tr>
          </thead>
          <tbody>
            {% for s in c.student_set.all %}
            <tr>
              <td>{{s.name}}</td>
              <td>
                <div class="btn-group btn-group-toggle" data-toggle="buttons">
                  <label class="btn btn-outline-success active">
                    <input
                      type="radio"
                      name="{{ s.USN }}"
                      id="option1"
                      autocomplete="off"
                      value="present"
                      checked
                    />
                    Present
                  </label>

                  <label class="btn btn-outline-danger">
                    <input
                      type="radio"
                      name="{{ s.USN }}"
                      id="option2"
                      autocomplete="off"
                      value="absent"
                    />
                    Absent
                  </label>
                </div>
              </td>
            </tr>
            {% endfor %}
          </tbody>
        </table>
      </div>
    </div>
  </div>

  <input class="btn btn-success" type="submit" value="Submit" />
</form>

{% else %}
<p>No students in Class</p>
{% endif %} {% endblock %}